# Generated by Django 3.0.5 on 2020-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casilla',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='y',
            field=models.IntegerField(),
        ),
    ]
