# Generated by Django 3.0.5 on 2020-05-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200522_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casilla',
            name='borde',
        ),
    ]
